config/routes.rb
Rails.application.routes.draw do
  resources :parties

  get 'pages/index'

    root 'pages#index'

end

app/models/party.rb
class Party < ActiveRecord::Base
	geocoded_by :address
	#http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  # GET /parties
  # GET /parties.json
  def index     
    @parties = Party.all
    @hash = Gmaps4rails.build_markers(@parties) do |party, marker|
    marker.lat party.latitude
    marker.lng party.longitude
    marker.picture({
      "url" => party.picture,
      "width" =>36,
      "height" =>36
      })
     contentString = "<div class='box' style='width:200px;'><h4><strong>"+party.name+", "+party.description+"</strong></h4><img src='"+party.picture+"' width='111' height='90' class=''></div>"
 
     marker.infowindow contentString    
  end


  end

  # GET /parties/1
  # GET /parties/1.json
  def show
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:name, :starts_at, :openbar, :address, :latitude, :longitude, :dress_code, :description, :disco_tweet ,:picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geolocal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
Bievenidos
<div id="demo">	
 
</div>

<script>
var x = document.getElementById("demo");
function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}
function showPosition(position) {
    x.innerHTML = "tu posicion es Latitude: " + position.coords.latitude + "logitude "+ position.coords.longitude; 
    console.log(position.coords.latitude);
    console.log(position.coords.longitude);
    console.log("blabla");

}

getLocation();
</script>

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :starts_at %><br>
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :openbar %><br>
    <%= f.check_box :openbar %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :dress_code %><br>
    <%= f.text_field :dress_code %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :disco_tweet %><br>
    <%= f.text_field :disco_tweet %>
  </div>

   <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<p id="notice"><%= notice %></p>

Bievenidos
<div id="demo"> 
 
</div>


<h1>Listing Parties</h1>
<%= link_to 'New Party', new_party_path %>
<br>
<div style='width: 800px; border:1px solid black;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

 
<table style="border:1px solid black;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Starts at</th>
      <th>Openbar</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Dress code</th>
      <th>Description</th>
      <th>Disco tweet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.name %></td>
        <td><%= party.starts_at %></td>
        <td><%= party.openbar %></td>
        <td><%= party.address %></td>
        <td><%= party.latitude %></td>
        <td><%= party.longitude %></td>
        <td><%= party.dress_code %></td>
        <td><%= party.description %></td>
        <td><%= party.disco_tweet %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>

<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<script>

handler = Gmaps.build('Google');
handler.buildMap({
    provider: {
      disableDefaultUI: true
      // pass in other Google Maps API options here
    },
    internal: {
      id: 'map'
    }
  },
  function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  }
);
 
 
var x = document.getElementById("demo");
function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}
function showPosition(position) {
    x.innerHTML = "tu posicion es Latitude: " + position.coords.latitude + "logitude "+ position.coords.longitude; 
    console.log(position.coords.latitude);
    console.log(position.coords.longitude);
    console.log("blabla");

}

getLocation();
 
</script>
 

app/views/parties/new.html.erb
<h1>New Party</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @party.name %>
</p>

<p>
  <strong>Starts at:</strong>
  <%= @party.starts_at %>
</p>

<p>
  <strong>Openbar:</strong>
  <%= @party.openbar %>
</p>

<p>
  <strong>Address:</strong>
  <%= @party.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @party.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @party.longitude %>
</p>

<p>
  <strong>Dress code:</strong>
  <%= @party.dress_code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @party.description %>
</p>

<p>
  <strong>Disco tweet:</strong>
  <%= @party.disco_tweet %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @party.picture %>
</p>



<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>